import { DEFAULT_PREFERENCES } from "@/lib/preferences";
import type { Agreement, Profile, Timepiece } from "@/lib/types";

export const DEMO_PROFILE: Profile = {
  name: "Jonathan Hale",
  email: "jonathan.hale@mechartcap.com",
  phone: "+1 (212) 555-0148",
  member: false,
  avatar: "/watches/patek-wrist.jpg",
  role: "collector",
  onboardingComplete: true,
  applicationSubmitted: true,
  preferences: { ...DEFAULT_PREFERENCES },
};

export const ADMIN_PROFILE: Profile = {
  name: "Ricardo Cidale",
  email: "admin@mechartcap.com",
  phone: "+1 (833) 209-0972",
  member: true,
  avatar: "/brand/logo-ff-mark.png",
  role: "admin",
  onboardingComplete: true,
  preferences: { ...DEFAULT_PREFERENCES },
};

export const STAFF_PROFILE: Profile = {
  name: "Desk Appraiser",
  email: "desk@mechartcap.com",
  phone: "+1 (833) 209-0972",
  member: true,
  avatar: "/brand/logo-ff-mark.png",
  role: "appraiser",
  onboardingComplete: true,
  preferences: { ...DEFAULT_PREFERENCES },
};

export const DEMO_TIMEPIECES: Timepiece[] = [
  {
    id: "rm-011",
    ownerEmail: "jonathan.hale@mechartcap.com",
    assetCode: "20210321-RM011",
    brand: "Richard Mille",
    model: "RM 011",
    reference: "RM 011",
    images: ["/watches/richard-mille.jpg", "/watches/richard-mille-side.jpg"],
    status: "appraised",
    valueLow: 280000,
    valueHigh: 350000,
    financeable: true,
    condition: "Mint",
    boxPapers: "Box and papers",
    caseMetal: "Rose gold",
    caseType: "Tonneau",
    caseDiameter: "44mm",
    dialColor: "Skeleton",
    buckle: "Folding clasp",
    band: "strap",
    bandMaterial: "Rubber",
    complication: "Chronograph",
    evaluatedAt: "2021-03-21",
  },
  {
    id: "pp-nautilus",
    ownerEmail: "jonathan.hale@mechartcap.com",
    assetCode: "20210321-PP5711",
    brand: "Patek Philippe",
    model: "Nautilus",
    reference: "5711/1A",
    images: ["/watches/patek-nautilus.jpg", "/watches/patek-wrist.jpg"],
    status: "appraised",
    valueLow: 95000,
    valueHigh: 120000,
    financeable: true,
    condition: "Unworn",
    boxPapers: "Box and papers",
    caseMetal: "Steel",
    caseType: "Round",
    caseDiameter: "40mm",
    dialColor: "Blue",
    buckle: "Folding clasp",
    band: "bracelet",
    bandMaterial: "Steel",
    complication: "Date",
    evaluatedAt: "2021-03-21",
  },
  {
    id: "ap-royal-oak",
    ownerEmail: "jonathan.hale@mechartcap.com",
    assetCode: "20210321-AP15400",
    brand: "Audemars Piguet",
    model: "Royal Oak Selfwinding",
    reference: "15400ST",
    images: ["/watches/royal-oak.jpg"],
    status: "reviewing",
    valueLow: 38000,
    valueHigh: 48000,
    financeable: true,
    condition: "Unworn",
    boxPapers: "Box and papers",
    caseMetal: "Steel",
    caseType: "Round",
    caseDiameter: "41mm",
    dialColor: "Blue",
    buckle: "AP folding clasp",
    band: "bracelet",
    bandMaterial: "Steel",
    complication: "Date",
  },
  {
    id: "rg-logical-one",
    ownerEmail: "jonathan.hale@mechartcap.com",
    assetCode: "20210321-RGLO",
    brand: "Romain Gauthier",
    model: "Logical One",
    images: ["/watches/romain-gauthier.jpg"],
    status: "not_evaluated",
    financeable: true,
    condition: "Excellent",
    boxPapers: "Box and papers",
    caseMetal: "White gold",
    caseType: "Round",
    caseDiameter: "43mm",
    dialColor: "Silver",
    buckle: "Pin buckle",
    band: "strap",
    bandMaterial: "Alligator",
    complication: "Time only",
  },
];

export const DEMO_AGREEMENTS: Agreement[] = [
  {
    id: "agr-31419",
    agreementCode: "MAC-31419",
    watchIds: ["rm-011", "pp-nautilus"],
    amount: 200000,
    termMonths: 12,
    delivery: "Desk arranges intake",
    ownerName: "Jonathan Hale",
    email: "jonathan.hale@mechartcap.com",
    // Already on the book since 2021 with its pieces held, so the demo reads
    // past due. KTD21 maps rows of this vintage to executed on their created day.
    status: "executed",
    createdAt: "2021-03-14",
    executedOn: "2021-03-14",
    version: 1,
    lastActionAt: "2021-03-14T00:00:00.000Z",
  },
];
