export const MAC = {
  navy: "#0E2A44",
  gold: "#FCB040",
  champagne: "#E8D5C0",
  black: "#000000",
  ink: "#111111",
  field: "#0A0A0A",
  parchment: "#F3EEE6",
} as const;

export const DEFAULT_SETTINGS = {
  companyName: "Mechanical Art Capital",
  phone: "+1 (833) 209-0972",
  email: "info@mechartcap.com",
  financingEmail: "financing@mechartcap.com",
  handle: "@mechartcap",
  startingRate: 0.185,
  minAdvance: 10_000,
  maxLtv: 0.6,
  setupFee: 0.01,
  earlyRepurchaseAmount: 0.035,
  brokerFee: 0.035,
  minMonths: 3,
  earlyStartMonth: 4,
  earlyUntilMonth: 8,
  typicalTerm: 12,
  membershipMonthly: 4.99,
  minPieceValue: 40_000,
  closeBusinessDays: 2,
  vaultLocation: "Manhattan vault",
  requireFourPhotos: true,
  ageMinimum: 18,
  allowVideo: true,
  appearance: "dark" as const,
};
